/* eslint-disable linebreak-style */
export { default as Login } from './Login'
export { default as Account } from './Account'
export { default as Dashboard } from './Dashboard'
export { default as Icons } from './Icons'
export { default as NotFound } from './NotFound'
export { default as ProductList } from './ProductList'
export { default as Settings } from './Settings'
export { default as SignUp } from './SignUp'
export { default as Typography } from './Typography'
export { default as UserList } from './UserList'
export { default as Users } from './Users'
export { default as Customers } from './Customers'
export { default as PaymentSlips } from './PaymentSlips'
export { default as Discount } from './Discounts'
export { default as Tickets } from './Tickets'
export { default as Services } from './Services'
export { default as Rooms } from './Rooms'
